export interface IsoCountry {
  code: string;
  name: string;
  defaultCurrency: string;
  callingCode: string;
}

export const ISO_COUNTRIES: readonly IsoCountry[] = [
  { code: 'AD', name: 'Andorra', defaultCurrency: 'EUR', callingCode: '+376' },
  { code: 'AE', name: 'United Arab Emirates', defaultCurrency: 'AED', callingCode: '+971' },
  { code: 'AF', name: 'Afghanistan', defaultCurrency: 'AFN', callingCode: '+93' },
  { code: 'AG', name: 'Antigua and Barbuda', defaultCurrency: 'XCD', callingCode: '+1268' },
  { code: 'AI', name: 'Anguilla', defaultCurrency: 'XCD', callingCode: '+1264' },
  { code: 'AL', name: 'Albania', defaultCurrency: 'ALL', callingCode: '+355' },
  { code: 'AM', name: 'Armenia', defaultCurrency: 'AMD', callingCode: '+374' },
  { code: 'AO', name: 'Angola', defaultCurrency: 'AOA', callingCode: '+244' },
  { code: 'AQ', name: 'Antarctica', defaultCurrency: 'USD', callingCode: '+672' },
  { code: 'AR', name: 'Argentina', defaultCurrency: 'ARS', callingCode: '+54' },
  { code: 'AS', name: 'American Samoa', defaultCurrency: 'USD', callingCode: '+1684' },
  { code: 'AT', name: 'Austria', defaultCurrency: 'EUR', callingCode: '+43' },
  { code: 'AU', name: 'Australia', defaultCurrency: 'AUD', callingCode: '+61' },
  { code: 'AW', name: 'Aruba', defaultCurrency: 'AWG', callingCode: '+297' },
  { code: 'AX', name: 'Åland Islands', defaultCurrency: 'EUR', callingCode: '+358' },
  { code: 'AZ', name: 'Azerbaijan', defaultCurrency: 'AZN', callingCode: '+994' },
  { code: 'BA', name: 'Bosnia and Herzegovina', defaultCurrency: 'BAM', callingCode: '+387' },
  { code: 'BB', name: 'Barbados', defaultCurrency: 'BBD', callingCode: '+1246' },
  { code: 'BD', name: 'Bangladesh', defaultCurrency: 'BDT', callingCode: '+880' },
  { code: 'BE', name: 'Belgium', defaultCurrency: 'EUR', callingCode: '+32' },
  { code: 'BF', name: 'Burkina Faso', defaultCurrency: 'XOF', callingCode: '+226' },
  { code: 'BG', name: 'Bulgaria', defaultCurrency: 'BGN', callingCode: '+359' },
  { code: 'BH', name: 'Bahrain', defaultCurrency: 'BHD', callingCode: '+973' },
  { code: 'BI', name: 'Burundi', defaultCurrency: 'BIF', callingCode: '+257' },
  { code: 'BJ', name: 'Benin', defaultCurrency: 'XOF', callingCode: '+229' },
  { code: 'BL', name: 'Saint Barthélemy', defaultCurrency: 'EUR', callingCode: '+590' },
  { code: 'BM', name: 'Bermuda', defaultCurrency: 'BMD', callingCode: '+1441' },
  { code: 'BN', name: 'Brunei Darussalam', defaultCurrency: 'BND', callingCode: '+673' },
  { code: 'BO', name: 'Bolivia', defaultCurrency: 'BOB', callingCode: '+591' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', defaultCurrency: 'USD', callingCode: '+599' },
  { code: 'BR', name: 'Brazil', defaultCurrency: 'BRL', callingCode: '+55' },
  { code: 'BS', name: 'Bahamas', defaultCurrency: 'BSD', callingCode: '+1242' },
  { code: 'BT', name: 'Bhutan', defaultCurrency: 'BTN', callingCode: '+975' },
  { code: 'BV', name: 'Bouvet Island', defaultCurrency: 'NOK', callingCode: '+47' },
  { code: 'BW', name: 'Botswana', defaultCurrency: 'BWP', callingCode: '+267' },
  { code: 'BY', name: 'Belarus', defaultCurrency: 'BYN', callingCode: '+375' },
  { code: 'BZ', name: 'Belize', defaultCurrency: 'BZD', callingCode: '+501' },
  { code: 'CA', name: 'Canada', defaultCurrency: 'CAD', callingCode: '+1' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', defaultCurrency: 'AUD', callingCode: '+61' },
  { code: 'CD', name: 'Congo, Democratic Republic of the', defaultCurrency: 'CDF', callingCode: '+243' },
  { code: 'CF', name: 'Central African Republic', defaultCurrency: 'XAF', callingCode: '+236' },
  { code: 'CG', name: 'Congo', defaultCurrency: 'XAF', callingCode: '+242' },
  { code: 'CH', name: 'Switzerland', defaultCurrency: 'CHF', callingCode: '+41' },
  { code: 'CI', name: "Côte d'Ivoire", defaultCurrency: 'XOF', callingCode: '+225' },
  { code: 'CK', name: 'Cook Islands', defaultCurrency: 'NZD', callingCode: '+682' },
  { code: 'CL', name: 'Chile', defaultCurrency: 'CLP', callingCode: '+56' },
  { code: 'CM', name: 'Cameroon', defaultCurrency: 'XAF', callingCode: '+237' },
  { code: 'CN', name: 'China', defaultCurrency: 'CNY', callingCode: '+86' },
  { code: 'CO', name: 'Colombia', defaultCurrency: 'COP', callingCode: '+57' },
  { code: 'CR', name: 'Costa Rica', defaultCurrency: 'CRC', callingCode: '+506' },
  { code: 'CU', name: 'Cuba', defaultCurrency: 'CUP', callingCode: '+53' },
  { code: 'CV', name: 'Cabo Verde', defaultCurrency: 'CVE', callingCode: '+238' },
  { code: 'CW', name: 'Curaçao', defaultCurrency: 'ANG', callingCode: '+599' },
  { code: 'CX', name: 'Christmas Island', defaultCurrency: 'AUD', callingCode: '+61' },
  { code: 'CY', name: 'Cyprus', defaultCurrency: 'EUR', callingCode: '+357' },
  { code: 'CZ', name: 'Czechia', defaultCurrency: 'CZK', callingCode: '+420' },
  { code: 'DE', name: 'Germany', defaultCurrency: 'EUR', callingCode: '+49' },
  { code: 'DJ', name: 'Djibouti', defaultCurrency: 'DJF', callingCode: '+253' },
  { code: 'DK', name: 'Denmark', defaultCurrency: 'DKK', callingCode: '+45' },
  { code: 'DM', name: 'Dominica', defaultCurrency: 'XCD', callingCode: '+1767' },
  { code: 'DO', name: 'Dominican Republic', defaultCurrency: 'DOP', callingCode: '+1809' },
  { code: 'DZ', name: 'Algeria', defaultCurrency: 'DZD', callingCode: '+213' },
  { code: 'EC', name: 'Ecuador', defaultCurrency: 'USD', callingCode: '+593' },
  { code: 'EE', name: 'Estonia', defaultCurrency: 'EUR', callingCode: '+372' },
  { code: 'EG', name: 'Egypt', defaultCurrency: 'EGP', callingCode: '+20' },
  { code: 'EH', name: 'Western Sahara', defaultCurrency: 'MAD', callingCode: '+212' },
  { code: 'ER', name: 'Eritrea', defaultCurrency: 'ERN', callingCode: '+291' },
  { code: 'ES', name: 'Spain', defaultCurrency: 'EUR', callingCode: '+34' },
  { code: 'ET', name: 'Ethiopia', defaultCurrency: 'ETB', callingCode: '+251' },
  { code: 'FI', name: 'Finland', defaultCurrency: 'EUR', callingCode: '+358' },
  { code: 'FJ', name: 'Fiji', defaultCurrency: 'FJD', callingCode: '+679' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', defaultCurrency: 'FKP', callingCode: '+500' },
  { code: 'FM', name: 'Micronesia (Federated States of)', defaultCurrency: 'USD', callingCode: '+691' },
  { code: 'FO', name: 'Faroe Islands', defaultCurrency: 'DKK', callingCode: '+298' },
  { code: 'FR', name: 'France', defaultCurrency: 'EUR', callingCode: '+33' },
  { code: 'GA', name: 'Gabon', defaultCurrency: 'XAF', callingCode: '+241' },
  { code: 'GB', name: 'United Kingdom', defaultCurrency: 'GBP', callingCode: '+44' },
  { code: 'GD', name: 'Grenada', defaultCurrency: 'XCD', callingCode: '+1473' },
  { code: 'GE', name: 'Georgia', defaultCurrency: 'GEL', callingCode: '+995' },
  { code: 'GF', name: 'French Guiana', defaultCurrency: 'EUR', callingCode: '+594' },
  { code: 'GG', name: 'Guernsey', defaultCurrency: 'GBP', callingCode: '+44' },
  { code: 'GH', name: 'Ghana', defaultCurrency: 'GHS', callingCode: '+233' },
  { code: 'GI', name: 'Gibraltar', defaultCurrency: 'GIP', callingCode: '+350' },
  { code: 'GL', name: 'Greenland', defaultCurrency: 'DKK', callingCode: '+299' },
  { code: 'GM', name: 'Gambia', defaultCurrency: 'GMD', callingCode: '+220' },
  { code: 'GN', name: 'Guinea', defaultCurrency: 'GNF', callingCode: '+224' },
  { code: 'GP', name: 'Guadeloupe', defaultCurrency: 'EUR', callingCode: '+590' },
  { code: 'GQ', name: 'Equatorial Guinea', defaultCurrency: 'XAF', callingCode: '+240' },
  { code: 'GR', name: 'Greece', defaultCurrency: 'EUR', callingCode: '+30' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', defaultCurrency: 'GBP', callingCode: '+500' },
  { code: 'GT', name: 'Guatemala', defaultCurrency: 'GTQ', callingCode: '+502' },
  { code: 'GU', name: 'Guam', defaultCurrency: 'USD', callingCode: '+1671' },
  { code: 'GW', name: 'Guinea-Bissau', defaultCurrency: 'XOF', callingCode: '+245' },
  { code: 'GY', name: 'Guyana', defaultCurrency: 'GYD', callingCode: '+592' },
  { code: 'HK', name: 'Hong Kong', defaultCurrency: 'HKD', callingCode: '+852' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', defaultCurrency: 'AUD', callingCode: '+672' },
  { code: 'HN', name: 'Honduras', defaultCurrency: 'HNL', callingCode: '+504' },
  { code: 'HR', name: 'Croatia', defaultCurrency: 'EUR', callingCode: '+385' },
  { code: 'HT', name: 'Haiti', defaultCurrency: 'HTG', callingCode: '+509' },
  { code: 'HU', name: 'Hungary', defaultCurrency: 'HUF', callingCode: '+36' },
  { code: 'ID', name: 'Indonesia', defaultCurrency: 'IDR', callingCode: '+62' },
  { code: 'IE', name: 'Ireland', defaultCurrency: 'EUR', callingCode: '+353' },
  { code: 'IL', name: 'Israel', defaultCurrency: 'ILS', callingCode: '+972' },
  { code: 'IM', name: 'Isle of Man', defaultCurrency: 'GBP', callingCode: '+44' },
  { code: 'IN', name: 'India', defaultCurrency: 'INR', callingCode: '+91' },
  { code: 'IO', name: 'British Indian Ocean Territory', defaultCurrency: 'USD', callingCode: '+246' },
  { code: 'IQ', name: 'Iraq', defaultCurrency: 'IQD', callingCode: '+964' },
  { code: 'IR', name: 'Iran', defaultCurrency: 'IRR', callingCode: '+98' },
  { code: 'IS', name: 'Iceland', defaultCurrency: 'ISK', callingCode: '+354' },
  { code: 'IT', name: 'Italy', defaultCurrency: 'EUR', callingCode: '+39' },
  { code: 'JE', name: 'Jersey', defaultCurrency: 'GBP', callingCode: '+44' },
  { code: 'JM', name: 'Jamaica', defaultCurrency: 'JMD', callingCode: '+1876' },
  { code: 'JO', name: 'Jordan', defaultCurrency: 'JOD', callingCode: '+962' },
  { code: 'JP', name: 'Japan', defaultCurrency: 'JPY', callingCode: '+81' },
  { code: 'KE', name: 'Kenya', defaultCurrency: 'KES', callingCode: '+254' },
  { code: 'KG', name: 'Kyrgyzstan', defaultCurrency: 'KGS', callingCode: '+996' },
  { code: 'KH', name: 'Cambodia', defaultCurrency: 'KHR', callingCode: '+855' },
  { code: 'KI', name: 'Kiribati', defaultCurrency: 'AUD', callingCode: '+686' },
  { code: 'KM', name: 'Comoros', defaultCurrency: 'KMF', callingCode: '+269' },
  { code: 'KN', name: 'Saint Kitts and Nevis', defaultCurrency: 'XCD', callingCode: '+1869' },
  { code: 'KP', name: "Korea (Democratic People's Republic of)", defaultCurrency: 'KPW', callingCode: '+850' },
  { code: 'KR', name: 'Korea (Republic of)', defaultCurrency: 'KRW', callingCode: '+82' },
  { code: 'KW', name: 'Kuwait', defaultCurrency: 'KWD', callingCode: '+965' },
  { code: 'KY', name: 'Cayman Islands', defaultCurrency: 'KYD', callingCode: '+1345' },
  { code: 'KZ', name: 'Kazakhstan', defaultCurrency: 'KZT', callingCode: '+7' },
  { code: 'LA', name: "Lao People's Democratic Republic", defaultCurrency: 'LAK', callingCode: '+856' },
  { code: 'LB', name: 'Lebanon', defaultCurrency: 'LBP', callingCode: '+961' },
  { code: 'LC', name: 'Saint Lucia', defaultCurrency: 'XCD', callingCode: '+1758' },
  { code: 'LI', name: 'Liechtenstein', defaultCurrency: 'CHF', callingCode: '+423' },
  { code: 'LK', name: 'Sri Lanka', defaultCurrency: 'LKR', callingCode: '+94' },
  { code: 'LR', name: 'Liberia', defaultCurrency: 'LRD', callingCode: '+231' },
  { code: 'LS', name: 'Lesotho', defaultCurrency: 'LSL', callingCode: '+266' },
  { code: 'LT', name: 'Lithuania', defaultCurrency: 'EUR', callingCode: '+370' },
  { code: 'LU', name: 'Luxembourg', defaultCurrency: 'EUR', callingCode: '+352' },
  { code: 'LV', name: 'Latvia', defaultCurrency: 'EUR', callingCode: '+371' },
  { code: 'LY', name: 'Libya', defaultCurrency: 'LYD', callingCode: '+218' },
  { code: 'MA', name: 'Morocco', defaultCurrency: 'MAD', callingCode: '+212' },
  { code: 'MC', name: 'Monaco', defaultCurrency: 'EUR', callingCode: '+377' },
  { code: 'MD', name: 'Moldova', defaultCurrency: 'MDL', callingCode: '+373' },
  { code: 'ME', name: 'Montenegro', defaultCurrency: 'EUR', callingCode: '+382' },
  { code: 'MF', name: 'Saint Martin (French part)', defaultCurrency: 'EUR', callingCode: '+590' },
  { code: 'MG', name: 'Madagascar', defaultCurrency: 'MGA', callingCode: '+261' },
  { code: 'MH', name: 'Marshall Islands', defaultCurrency: 'USD', callingCode: '+692' },
  { code: 'MK', name: 'North Macedonia', defaultCurrency: 'MKD', callingCode: '+389' },
  { code: 'ML', name: 'Mali', defaultCurrency: 'XOF', callingCode: '+223' },
  { code: 'MM', name: 'Myanmar', defaultCurrency: 'MMK', callingCode: '+95' },
  { code: 'MN', name: 'Mongolia', defaultCurrency: 'MNT', callingCode: '+976' },
  { code: 'MO', name: 'Macao', defaultCurrency: 'MOP', callingCode: '+853' },
  { code: 'MP', name: 'Northern Mariana Islands', defaultCurrency: 'USD', callingCode: '+1670' },
  { code: 'MQ', name: 'Martinique', defaultCurrency: 'EUR', callingCode: '+596' },
  { code: 'MR', name: 'Mauritania', defaultCurrency: 'MRU', callingCode: '+222' },
  { code: 'MS', name: 'Montserrat', defaultCurrency: 'XCD', callingCode: '+1664' },
  { code: 'MT', name: 'Malta', defaultCurrency: 'EUR', callingCode: '+356' },
  { code: 'MU', name: 'Mauritius', defaultCurrency: 'MUR', callingCode: '+230' },
  { code: 'MV', name: 'Maldives', defaultCurrency: 'MVR', callingCode: '+960' },
  { code: 'MW', name: 'Malawi', defaultCurrency: 'MWK', callingCode: '+265' },
  { code: 'MX', name: 'Mexico', defaultCurrency: 'MXN', callingCode: '+52' },
  { code: 'MY', name: 'Malaysia', defaultCurrency: 'MYR', callingCode: '+60' },
  { code: 'MZ', name: 'Mozambique', defaultCurrency: 'MZN', callingCode: '+258' },
  { code: 'NA', name: 'Namibia', defaultCurrency: 'NAD', callingCode: '+264' },
  { code: 'NC', name: 'New Caledonia', defaultCurrency: 'XPF', callingCode: '+687' },
  { code: 'NE', name: 'Niger', defaultCurrency: 'XOF', callingCode: '+227' },
  { code: 'NF', name: 'Norfolk Island', defaultCurrency: 'AUD', callingCode: '+672' },
  { code: 'NG', name: 'Nigeria', defaultCurrency: 'NGN', callingCode: '+234' },
  { code: 'NI', name: 'Nicaragua', defaultCurrency: 'NIO', callingCode: '+505' },
  { code: 'NL', name: 'Netherlands', defaultCurrency: 'EUR', callingCode: '+31' },
  { code: 'NO', name: 'Norway', defaultCurrency: 'NOK', callingCode: '+47' },
  { code: 'NP', name: 'Nepal', defaultCurrency: 'NPR', callingCode: '+977' },
  { code: 'NR', name: 'Nauru', defaultCurrency: 'AUD', callingCode: '+674' },
  { code: 'NU', name: 'Niue', defaultCurrency: 'NZD', callingCode: '+683' },
  { code: 'NZ', name: 'New Zealand', defaultCurrency: 'NZD', callingCode: '+64' },
  { code: 'OM', name: 'Oman', defaultCurrency: 'OMR', callingCode: '+968' },
  { code: 'PA', name: 'Panama', defaultCurrency: 'PAB', callingCode: '+507' },
  { code: 'PE', name: 'Peru', defaultCurrency: 'PEN', callingCode: '+51' },
  { code: 'PF', name: 'French Polynesia', defaultCurrency: 'XPF', callingCode: '+689' },
  { code: 'PG', name: 'Papua New Guinea', defaultCurrency: 'PGK', callingCode: '+675' },
  { code: 'PH', name: 'Philippines', defaultCurrency: 'PHP', callingCode: '+63' },
  { code: 'PK', name: 'Pakistan', defaultCurrency: 'PKR', callingCode: '+92' },
  { code: 'PL', name: 'Poland', defaultCurrency: 'PLN', callingCode: '+48' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', defaultCurrency: 'EUR', callingCode: '+508' },
  { code: 'PN', name: 'Pitcairn', defaultCurrency: 'NZD', callingCode: '+64' },
  { code: 'PR', name: 'Puerto Rico', defaultCurrency: 'USD', callingCode: '+1787' },
  { code: 'PS', name: 'Palestine, State of', defaultCurrency: 'ILS', callingCode: '+970' },
  { code: 'PT', name: 'Portugal', defaultCurrency: 'EUR', callingCode: '+351' },
  { code: 'PW', name: 'Palau', defaultCurrency: 'USD', callingCode: '+680' },
  { code: 'PY', name: 'Paraguay', defaultCurrency: 'PYG', callingCode: '+595' },
  { code: 'QA', name: 'Qatar', defaultCurrency: 'QAR', callingCode: '+974' },
  { code: 'RE', name: 'Réunion', defaultCurrency: 'EUR', callingCode: '+262' },
  { code: 'RO', name: 'Romania', defaultCurrency: 'RON', callingCode: '+40' },
  { code: 'RS', name: 'Serbia', defaultCurrency: 'RSD', callingCode: '+381' },
  { code: 'RU', name: 'Russian Federation', defaultCurrency: 'RUB', callingCode: '+7' },
  { code: 'RW', name: 'Rwanda', defaultCurrency: 'RWF', callingCode: '+250' },
  { code: 'SA', name: 'Saudi Arabia', defaultCurrency: 'SAR', callingCode: '+966' },
  { code: 'SB', name: 'Solomon Islands', defaultCurrency: 'SBD', callingCode: '+677' },
  { code: 'SC', name: 'Seychelles', defaultCurrency: 'SCR', callingCode: '+248' },
  { code: 'SD', name: 'Sudan', defaultCurrency: 'SDG', callingCode: '+249' },
  { code: 'SE', name: 'Sweden', defaultCurrency: 'SEK', callingCode: '+46' },
  { code: 'SG', name: 'Singapore', defaultCurrency: 'SGD', callingCode: '+65' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', defaultCurrency: 'SHP', callingCode: '+290' },
  { code: 'SI', name: 'Slovenia', defaultCurrency: 'EUR', callingCode: '+386' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', defaultCurrency: 'NOK', callingCode: '+47' },
  { code: 'SK', name: 'Slovakia', defaultCurrency: 'EUR', callingCode: '+421' },
  { code: 'SL', name: 'Sierra Leone', defaultCurrency: 'SLE', callingCode: '+232' },
  { code: 'SM', name: 'San Marino', defaultCurrency: 'EUR', callingCode: '+378' },
  { code: 'SN', name: 'Senegal', defaultCurrency: 'XOF', callingCode: '+221' },
  { code: 'SO', name: 'Somalia', defaultCurrency: 'SOS', callingCode: '+252' },
  { code: 'SR', name: 'Suriname', defaultCurrency: 'SRD', callingCode: '+597' },
  { code: 'SS', name: 'South Sudan', defaultCurrency: 'SSP', callingCode: '+211' },
  { code: 'ST', name: 'Sao Tome and Principe', defaultCurrency: 'STN', callingCode: '+239' },
  { code: 'SV', name: 'El Salvador', defaultCurrency: 'USD', callingCode: '+503' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', defaultCurrency: 'ANG', callingCode: '+1721' },
  { code: 'SY', name: 'Syrian Arab Republic', defaultCurrency: 'SYP', callingCode: '+963' },
  { code: 'SZ', name: 'Eswatini', defaultCurrency: 'SZL', callingCode: '+268' },
  { code: 'TC', name: 'Turks and Caicos Islands', defaultCurrency: 'USD', callingCode: '+1649' },
  { code: 'TD', name: 'Chad', defaultCurrency: 'XAF', callingCode: '+235' },
  { code: 'TF', name: 'French Southern Territories', defaultCurrency: 'EUR', callingCode: '+262' },
  { code: 'TG', name: 'Togo', defaultCurrency: 'XOF', callingCode: '+228' },
  { code: 'TH', name: 'Thailand', defaultCurrency: 'THB', callingCode: '+66' },
  { code: 'TJ', name: 'Tajikistan', defaultCurrency: 'TJS', callingCode: '+992' },
  { code: 'TK', name: 'Tokelau', defaultCurrency: 'NZD', callingCode: '+690' },
  { code: 'TL', name: 'Timor-Leste', defaultCurrency: 'USD', callingCode: '+670' },
  { code: 'TM', name: 'Turkmenistan', defaultCurrency: 'TMT', callingCode: '+993' },
  { code: 'TN', name: 'Tunisia', defaultCurrency: 'TND', callingCode: '+216' },
  { code: 'TO', name: 'Tonga', defaultCurrency: 'TOP', callingCode: '+676' },
  { code: 'TR', name: 'Türkiye', defaultCurrency: 'TRY', callingCode: '+90' },
  { code: 'TT', name: 'Trinidad and Tobago', defaultCurrency: 'TTD', callingCode: '+1868' },
  { code: 'TV', name: 'Tuvalu', defaultCurrency: 'AUD', callingCode: '+688' },
  { code: 'TW', name: 'Taiwan (Province of China)', defaultCurrency: 'TWD', callingCode: '+886' },
  { code: 'TZ', name: 'Tanzania, United Republic of', defaultCurrency: 'TZS', callingCode: '+255' },
  { code: 'UA', name: 'Ukraine', defaultCurrency: 'UAH', callingCode: '+380' },
  { code: 'UG', name: 'Uganda', defaultCurrency: 'UGX', callingCode: '+256' },
  { code: 'UM', name: 'United States Minor Outlying Islands', defaultCurrency: 'USD', callingCode: '+1' },
  { code: 'US', name: 'United States of America', defaultCurrency: 'USD', callingCode: '+1' },
  { code: 'UY', name: 'Uruguay', defaultCurrency: 'UYU', callingCode: '+598' },
  { code: 'UZ', name: 'Uzbekistan', defaultCurrency: 'UZS', callingCode: '+998' },
  { code: 'VA', name: 'Holy See', defaultCurrency: 'EUR', callingCode: '+379' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', defaultCurrency: 'XCD', callingCode: '+1784' },
  { code: 'VE', name: 'Venezuela (Bolivarian Republic of)', defaultCurrency: 'VES', callingCode: '+58' },
  { code: 'VG', name: 'Virgin Islands (British)', defaultCurrency: 'USD', callingCode: '+1284' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', defaultCurrency: 'USD', callingCode: '+1340' },
  { code: 'VN', name: 'Viet Nam', defaultCurrency: 'VND', callingCode: '+84' },
  { code: 'VU', name: 'Vanuatu', defaultCurrency: 'VUV', callingCode: '+678' },
  { code: 'WF', name: 'Wallis and Futuna', defaultCurrency: 'XPF', callingCode: '+681' },
  { code: 'WS', name: 'Samoa', defaultCurrency: 'WST', callingCode: '+685' },
  { code: 'YE', name: 'Yemen', defaultCurrency: 'YER', callingCode: '+967' },
  { code: 'YT', name: 'Mayotte', defaultCurrency: 'EUR', callingCode: '+262' },
  { code: 'ZA', name: 'South Africa', defaultCurrency: 'ZAR', callingCode: '+27' },
  { code: 'ZM', name: 'Zambia', defaultCurrency: 'ZMW', callingCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', defaultCurrency: 'ZWG', callingCode: '+263' },
];

export const ISO_COUNTRY_CODES: ReadonlySet<string> = new Set(ISO_COUNTRIES.map((country) => country.code));
